services:
    web:
        build:
            context: .
        env_file:
            - ".env"
        environment:
            - DB_NAME=${DB_NAME:-master}
            - DB_PASSWORD=${DB_PASSWORD:-__default}
            - DB_USER=${DB_USER:-postgres}
            - DB_HOST=${DB_HOST:-db}
            - DB_PORT=${DB_PORT:-5432}
            - PUID=${PUID:-1000}
            - PGID=${PGID:-1000}
        ports:
            - "${PORT:-80}:${PORT:-3000}"
        depends_on:
            db:
                condition: service_healthy
        volumes:
          - videos:/uploads/videos
        networks:
            - bridget
        

    db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=${DB_NAME:-master}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-__default}
            - POSTGRES_USER=${DB_USER:-postgres}
            - PGDATA=/data/pgdata
        volumes:
            - postgres_data:/data/pgdata
        healthcheck:
            interval: 5s
            timeout: 10s
            retries: 10
            test: pg_isready -h localhost -U $$POSTGRES_USER
        networks:
            - bridget

volumes:
    postgres_data:
    videos:

networks:
    bridget: